# Site settings
name: 记录点滴
email: 18630070626@126.com
author: 七步
url: 
resume_site: 
github: https://github.com/duan847/
baseurl: "/blog"
description: 记录点滴，整理思绪
meta_description: 七步;个人博客;程序员;IT;JAVA;
motto: 天行健君子以自强不息.
banner: 古七步断肠散。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: duan847

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

